### ISSUE TITLE
[1.14.4] Missing tools and texture and issues with Forge .81 - concurrent.ExecutionException: java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by ProsperCraft** [stfwi/engineers-tools#3] opened 2019-09-01 13:17 UTC
Loaded with only Engineers Tools-

![2019-09-01_07 13 34](https://user-images.githubusercontent.com/4427684/64076926-4498e480-cc88-11e9-8769-f84bd8701c83.png)

Logs-
[latest.log](https://github.com/stfwi/engineers-tools/files/3563508/latest.log)
[debug.log](https://github.com/stfwi/engineers-tools/files/3563509/debug.log)

**Comment by stfwi** [comment] 2019-09-01 21:41
Hi Goshen, thanks man! Should be fixed in engineerstools-1.14.4-1.0.1-b2.jar (updated Forge dep to .81 and adapted to the new recipe condition handling).

Could you leave a quick confirmation note if the issue is fixed in your setup as well? cheers -

**Comment by stfwi** [comment] 2019-09-21 15:45
The mod is now on Forge 1.14.4-28.1.10, is this issue still unresolved?

**Comment by stfwi** [comment] 2019-10-02 08:24
Hi, I close this issue, as we are already far beyond the affected version. If something comes up just file another issue. Thanks again for testing and the detailed report data -

**Closed by stfwi** 2019-10-02 08:24 UTC
Labels: anomaly, approval-pending, mc1.14, obsolete
